version: '3'

services:
  node-app:
    build: .
    image: node-app
    environment:
      - MONGODB_URL=mongodb://127.0.0.1:27017/woofie-chat
      - PORT=10004
      - REDIS_HOST=127.0.0.1
      - REDIS_PORT=6379
    ports:
      - 10004:10004
    volumes:
      - .:/usr/src/node-app
      - /usr/src/node-app/node_modules
    network_mode: host