version: '3'

services:
  node-app:
    build: .
    image: node-app
    environment:
      - MONGODB_URL=mongodb://127.0.0.1:27017/woofie-chat
      - PORT=10004
      - REDIS_HOST=127.0.0.1
      - REDIS_PORT=6379
    ports:
      - 10004:10004
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/node-app
      - /usr/src/node-app/node_modules
    network_mode: host

  mongodb:
    image: mongo:4.2.1-bionic
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db
    network_mode: host
volumes:
  mongodb-data:


