version: '3'

services:

  mongodb:
    image: mongo:4.2.1-bionic
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db
    networks:
      - woofie-chat-network

  node-app:
    build: .
    image: node-app
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/woofie-chat
      - PORT=3000
    ports:
      - 9015:3000
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/node-app
      - /usr/src/node-app/node_modules
    networks:
      - woofie-chat-network

volumes:
  mongodb-data:


networks:
  woofie-chat-network:
    driver: bridge
